# Generated by Django 4.2.1 on 2023-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('n', 'novel'), ('s', 'story'), ('d', 'drama'), ('c', 'comedy'), ('t', 'tragedy'), ('p', 'poem'), ('f', 'fantasy'), ('a', 'artistic literature'), ('l', 'lyrics'), ('b', 'book')], default='b', help_text='Enter a book genre', max_length=2, unique=True),
        ),
    ]
