# Generated by Django 4.2.1 on 2023-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_language_options_book_like_language_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='like',
            field=models.ManyToManyField(related_name='book_post', to='catalog.rating', verbose_name='Лайки'),
        ),
    ]
