# Generated by Django 4.2.1 on 2023-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_book_image_alter_book_pdf_file_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('n', 'Роман'), ('s', 'История'), ('d', 'Драмма'), ('c', 'Коммедия'), ('t', 'Трагедия'), ('p', 'Поэма'), ('f', 'Фантастика'), ('a', 'Художественная литература'), ('l', 'Лирика'), ('w', 'Обучающие'), ('k', 'Детектив')], default='b', help_text='Enter a book genre', max_length=2, unique=True),
        ),
    ]
