# Generated by Django 4.2.1 on 2023-06-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
    ]
