# Generated by Django 4.2.1 on 2023-06-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_reviews_email_remove_reviews_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
