# Generated by Django 4.2.1 on 2023-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Дата комментария'),
        ),
    ]
