# Generated by Django 4.2.1 on 2023-06-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_profile_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='button',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='книга'),
        ),
    ]
