# Generated by Django 4.2.1 on 2023-06-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_profile_button_alter_profile_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='button',
            new_name='status',
        ),
    ]
