# Generated by Django 4.2.1 on 2023-06-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='book',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='книга'),
        ),
    ]
