# Generated by Django 4.2.1 on 2023-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_profile_status_alter_profile_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genres_set', to='catalog.genre', verbose_name='Жанр'),
        ),
    ]
