# Generated by Django 4.2.1 on 2023-06-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_book_image_alter_book_pdf_file_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file_book',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='Файл'),
        ),
    ]
